name: Jekyll site CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - name: 🛎 Check out master
         uses: actions/checkout@master
         with:
           fetch-depth: 1  
       - name: Set up Ruby 2.6
         uses: actions/setup-ruby@v1
         with:
           ruby-version: 2.6
         env:
           JEKYLL_ENV: production   
       - name: 🧪 Bundle Caching
         id: bundle-cache
         uses: actions/cache@v1
         with:
           path: vendor/bundle
           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
           restore-keys: |
             ${{ runner.os }}-gems-
       - name: 🧪 Bundle config
         run: |
           bundle config path vendor/bundle
       - name: 🧪 Bundle Install
         if: steps.bundle-cache.outputs.cache-hit != 'true'
         run: |
           bundle install
       - name: 🧪 Bundle Install locally
         if: steps.bundle-cache.outputs.cache-hit == 'true'
         run: |
           bundle install --local
       - name: 🧹 Creating tabs and categories
         run: |
             bash _scripts/sh/create_pages.sh
             bash _scripts/sh/dump_lastmod.sh
            
       - name: 🔨 Building jekyll site 
         run: |
             if [[ -d _site ]]; then
                 jekyll clean
             fi
             JEKYLL_ENV=production
             JEKYLL_ENV=production bundle exec jekyll build            
          
       - name: 🧹 Zipping and deploying
         env:
           DEPLOY_PASS: ${{ secrets.DEPLOY_PASSWORD }}   
         run: |
            if [[ -d _site ]]; then
                 cd _site;zip -q -r release.zip *
                 curl -X POST "https://penchev.com/upload.php" -H "Authorization: Basic $DEPLOY_PASS" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -F "file=@\"release.zip\""
            fi
